# Run `packer build packer.pkr.hcl` to bake ami ->
# inject ami into main.tf
source "amazon-ebs" "autogenerated_1" {
  ami_name      = "ubuntu-node-packer-v1"
  instance_type = "t2.micro"
  profile       = "default"
  region        = "us-west-2"
  # TODO: figure out how to automate getting latest 20.04 ami-id
  source_ami    = "ami-0c09c7eb16d3e8e70"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["mkdir /tmp/src"]
  }

  provisioner "file" {
    destination = "/tmp"
    source      = "../src"
  }

  # TODO: change this to script, and use same sh as in packer-test directory
  provisioner "shell" {
    inline = ["mv /tmp/src ~"]
  }

  #post-processor "manifest" {
  #  output = "output.json"
  #}
}
